services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: mindcheck
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - mindcheck_db_data:/var/lib/postgresql/data

volumes:
  mindcheck_db_data:
