/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DashboardStatsDto"];
                        "application/json": components["schemas"]["DashboardStatsDto"];
                        "text/json": components["schemas"]["DashboardStatsDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/flow-transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FlowTransitionDto"][];
                        "application/json": components["schemas"]["FlowTransitionDto"][];
                        "text/json": components["schemas"]["FlowTransitionDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateFlowTransitionRequest"];
                    "text/json": components["schemas"]["CreateFlowTransitionRequest"];
                    "application/*+json": components["schemas"]["CreateFlowTransitionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FlowTransitionDto"];
                        "application/json": components["schemas"]["FlowTransitionDto"];
                        "text/json": components["schemas"]["FlowTransitionDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/flow-transitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InstrumentSummaryDto"][];
                        "application/json": components["schemas"]["InstrumentSummaryDto"][];
                        "text/json": components["schemas"]["InstrumentSummaryDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateInstrumentRequest"];
                    "text/json": components["schemas"]["CreateInstrumentRequest"];
                    "application/*+json": components["schemas"]["CreateInstrumentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateInstrumentResponse"];
                        "application/json": components["schemas"]["CreateInstrumentResponse"];
                        "text/json": components["schemas"]["CreateInstrumentResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/instruments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InstrumentDetailDto"];
                        "application/json": components["schemas"]["InstrumentDetailDto"];
                        "text/json": components["schemas"]["InstrumentDetailDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"][];
                        "application/json": components["schemas"]["UserDto"][];
                        "text/json": components["schemas"]["UserDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateUserRequest"];
                    "text/json": components["schemas"]["CreateUserRequest"];
                    "application/*+json": components["schemas"]["CreateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"];
                        "application/json": components["schemas"]["UserDto"];
                        "text/json": components["schemas"]["UserDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"];
                        "application/json": components["schemas"]["UserDto"];
                        "text/json": components["schemas"]["UserDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateUserRequest"];
                    "text/json": components["schemas"]["UpdateUserRequest"];
                    "application/*+json": components["schemas"]["UpdateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"];
                        "application/json": components["schemas"]["UserDto"];
                        "text/json": components["schemas"]["UserDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                    "text/json": components["schemas"]["RegisterRequest"];
                    "application/*+json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthTokenResponse"];
                        "application/json": components["schemas"]["AuthTokenResponse"];
                        "text/json": components["schemas"]["AuthTokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthTokenResponse"];
                        "application/json": components["schemas"]["AuthTokenResponse"];
                        "text/json": components["schemas"]["AuthTokenResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Locked */
                423: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ForgotPasswordRequest"];
                    "text/json": components["schemas"]["ForgotPasswordRequest"];
                    "application/*+json": components["schemas"]["ForgotPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ForgotPasswordResponse"];
                        "application/json": components["schemas"]["ForgotPasswordResponse"];
                        "text/json": components["schemas"]["ForgotPasswordResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ResetPasswordRequest"];
                    "text/json": components["schemas"]["ResetPasswordRequest"];
                    "application/*+json": components["schemas"]["ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StartSessionResponse"];
                        "application/json": components["schemas"]["StartSessionResponse"];
                        "text/json": components["schemas"]["StartSessionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NextStepResponse"];
                        "application/json": components["schemas"]["NextStepResponse"];
                        "text/json": components["schemas"]["NextStepResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SubmitAnswerRequest"];
                    "text/json": components["schemas"]["SubmitAnswerRequest"];
                    "application/*+json": components["schemas"]["SubmitAnswerRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultResponse"];
                        "application/json": components["schemas"]["ResultResponse"];
                        "text/json": components["schemas"]["ResultResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthTokenResponse: {
            token?: string | null;
            /** Format: uuid */
            userId?: string;
            username?: string | null;
            role?: string | null;
        };
        ChoiceDto: {
            /** Format: int32 */
            choiceId?: number;
            label?: string | null;
            /** Format: int32 */
            orderNo?: number;
        };
        CreateChoiceRequest: {
            label?: string | null;
            /** Format: int32 */
            score?: number;
            /** Format: int32 */
            orderNo?: number;
        };
        CreateFlowTransitionRequest: {
            /** Format: int32 */
            fromInstrumentId?: number | null;
            conditionType?: string | null;
            /** Format: int32 */
            questionId?: number | null;
            conditionValue?: string | null;
            /** Format: int32 */
            toInstrumentId?: number;
        };
        CreateInstrumentRequest: {
            code?: string | null;
            name?: string | null;
            version?: string | null;
            source?: string | null;
            isActive?: boolean;
            questions?: components["schemas"]["CreateQuestionRequest"][] | null;
            scoringRules?: components["schemas"]["CreateScoringRuleRequest"][] | null;
            riskRules?: components["schemas"]["CreateRiskRuleRequest"][] | null;
        };
        CreateInstrumentResponse: {
            /** Format: int32 */
            instrumentId?: number;
            code?: string | null;
            questions?: components["schemas"]["CreatedQuestionDto"][] | null;
        };
        CreateQuestionRequest: {
            text?: string | null;
            /** Format: int32 */
            orderNo?: number;
            choices?: components["schemas"]["CreateChoiceRequest"][] | null;
        };
        CreateRiskRuleRequest: {
            /** Format: int32 */
            questionOrderNo?: number;
            operator?: string | null;
            /** Format: int32 */
            threshold?: number;
            action?: string | null;
        };
        CreateScoringRuleRequest: {
            /** Format: int32 */
            min?: number;
            /** Format: int32 */
            max?: number;
            level?: string | null;
            interpretation?: string | null;
            advice?: string | null;
        };
        CreateUserRequest: {
            username?: string | null;
            email?: string | null;
            password?: string | null;
            role?: string | null;
        };
        CreatedChoiceDto: {
            /** Format: int32 */
            choiceId?: number;
            label?: string | null;
            /** Format: int32 */
            score?: number;
            /** Format: int32 */
            orderNo?: number;
        };
        CreatedQuestionDto: {
            /** Format: int32 */
            questionId?: number;
            text?: string | null;
            /** Format: int32 */
            orderNo?: number;
            choices?: components["schemas"]["CreatedChoiceDto"][] | null;
        };
        DailyTrendPointDto: {
            /** Format: date */
            date?: string;
            /** Format: int32 */
            sessionCount?: number;
        };
        DashboardStatsDto: {
            levelBreakdown?: components["schemas"]["LevelBreakdownDto"][] | null;
            dailyTrend?: components["schemas"]["DailyTrendPointDto"][] | null;
        };
        FlowTransitionDto: {
            /** Format: int32 */
            id?: number;
            /** Format: int32 */
            fromInstrumentId?: number | null;
            fromInstrumentCode?: string | null;
            conditionType?: string | null;
            /** Format: int32 */
            questionId?: number | null;
            conditionValue?: string | null;
            /** Format: int32 */
            toInstrumentId?: number;
            toInstrumentCode?: string | null;
        };
        ForgotPasswordRequest: {
            email?: string | null;
        };
        ForgotPasswordResponse: {
            devResetLink?: string | null;
        };
        HelpResourceDto: {
            label?: string | null;
            contact?: string | null;
        };
        InstrumentDetailDto: {
            /** Format: int32 */
            instrumentId?: number;
            code?: string | null;
            name?: string | null;
            questions?: components["schemas"]["InstrumentDetailQuestionDto"][] | null;
        };
        InstrumentDetailQuestionDto: {
            /** Format: int32 */
            questionId?: number;
            text?: string | null;
            /** Format: int32 */
            orderNo?: number;
        };
        InstrumentResultDto: {
            instrumentCode?: string | null;
            /** Format: int32 */
            totalScore?: number;
            level?: string | null;
            interpretation?: string | null;
            advice?: string | null;
        };
        InstrumentSummaryDto: {
            /** Format: int32 */
            instrumentId?: number;
            code?: string | null;
            name?: string | null;
        };
        LevelBreakdownDto: {
            instrumentCode?: string | null;
            level?: string | null;
            /** Format: int32 */
            count?: number;
        };
        LoginRequest: {
            usernameOrEmail?: string | null;
            password?: string | null;
        };
        NextStepResponse: {
            isComplete?: boolean;
            question?: components["schemas"]["QuestionDto"];
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        QuestionDto: {
            /** Format: int32 */
            questionId?: number;
            text?: string | null;
            choices?: components["schemas"]["ChoiceDto"][] | null;
        };
        RegisterRequest: {
            username?: string | null;
            email?: string | null;
            password?: string | null;
        };
        ResetPasswordRequest: {
            token?: string | null;
            newPassword?: string | null;
        };
        ResultResponse: {
            isComplete?: boolean;
            nextAction?: string | null;
            results?: components["schemas"]["InstrumentResultDto"][] | null;
            helpResources?: components["schemas"]["HelpResourceDto"][] | null;
        };
        StartSessionResponse: {
            /** Format: uuid */
            sessionId?: string;
        };
        SubmitAnswerRequest: {
            /** Format: int32 */
            questionId?: number;
            /** Format: int32 */
            choiceId?: number;
        };
        UpdateUserRequest: {
            username?: string | null;
            email?: string | null;
            role?: string | null;
            password?: string | null;
        };
        UserDto: {
            /** Format: uuid */
            userId?: string;
            username?: string | null;
            email?: string | null;
            role?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
