// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MindCheck.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MindCheck.Infrastructure.Migrations
{
    [DbContext(typeof(MindCheckDbContext))]
    [Migration("20260910101718_AddPasswordResetToUsers")]
    partial class AddPasswordResetToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MindCheck.Domain.Entities.Choice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("label");

                    b.Property<int>("OrderNo")
                        .HasColumnType("integer")
                        .HasColumnName("order_no");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("Id")
                        .HasName("pk_choices");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_choices_question_id");

                    b.ToTable("choices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Label = "ไม่เลย",
                            OrderNo = 1,
                            QuestionId = 1,
                            Score = 0
                        },
                        new
                        {
                            Id = 12,
                            Label = "เล็กน้อย",
                            OrderNo = 2,
                            QuestionId = 1,
                            Score = 1
                        },
                        new
                        {
                            Id = 13,
                            Label = "ปานกลาง",
                            OrderNo = 3,
                            QuestionId = 1,
                            Score = 2
                        },
                        new
                        {
                            Id = 14,
                            Label = "มาก",
                            OrderNo = 4,
                            QuestionId = 1,
                            Score = 3
                        },
                        new
                        {
                            Id = 21,
                            Label = "ไม่เลย",
                            OrderNo = 1,
                            QuestionId = 2,
                            Score = 0
                        },
                        new
                        {
                            Id = 22,
                            Label = "เล็กน้อย",
                            OrderNo = 2,
                            QuestionId = 2,
                            Score = 1
                        },
                        new
                        {
                            Id = 23,
                            Label = "ปานกลาง",
                            OrderNo = 3,
                            QuestionId = 2,
                            Score = 2
                        },
                        new
                        {
                            Id = 24,
                            Label = "มาก",
                            OrderNo = 4,
                            QuestionId = 2,
                            Score = 3
                        },
                        new
                        {
                            Id = 31,
                            Label = "ไม่เลย",
                            OrderNo = 1,
                            QuestionId = 3,
                            Score = 0
                        },
                        new
                        {
                            Id = 32,
                            Label = "เล็กน้อย",
                            OrderNo = 2,
                            QuestionId = 3,
                            Score = 1
                        },
                        new
                        {
                            Id = 33,
                            Label = "ปานกลาง",
                            OrderNo = 3,
                            QuestionId = 3,
                            Score = 2
                        },
                        new
                        {
                            Id = 34,
                            Label = "มาก",
                            OrderNo = 4,
                            QuestionId = 3,
                            Score = 3
                        },
                        new
                        {
                            Id = 41,
                            Label = "ไม่เลย",
                            OrderNo = 1,
                            QuestionId = 4,
                            Score = 0
                        },
                        new
                        {
                            Id = 42,
                            Label = "เล็กน้อย",
                            OrderNo = 2,
                            QuestionId = 4,
                            Score = 1
                        },
                        new
                        {
                            Id = 43,
                            Label = "ปานกลาง",
                            OrderNo = 3,
                            QuestionId = 4,
                            Score = 2
                        },
                        new
                        {
                            Id = 44,
                            Label = "มาก",
                            OrderNo = 4,
                            QuestionId = 4,
                            Score = 3
                        },
                        new
                        {
                            Id = 51,
                            Label = "ไม่เลย",
                            OrderNo = 1,
                            QuestionId = 5,
                            Score = 0
                        },
                        new
                        {
                            Id = 52,
                            Label = "เล็กน้อย",
                            OrderNo = 2,
                            QuestionId = 5,
                            Score = 1
                        },
                        new
                        {
                            Id = 53,
                            Label = "ปานกลาง",
                            OrderNo = 3,
                            QuestionId = 5,
                            Score = 2
                        },
                        new
                        {
                            Id = 54,
                            Label = "มาก",
                            OrderNo = 4,
                            QuestionId = 5,
                            Score = 3
                        },
                        new
                        {
                            Id = 81,
                            Label = "ไม่เลย",
                            OrderNo = 1,
                            QuestionId = 8,
                            Score = 0
                        },
                        new
                        {
                            Id = 82,
                            Label = "เล็กน้อย",
                            OrderNo = 2,
                            QuestionId = 8,
                            Score = 1
                        },
                        new
                        {
                            Id = 83,
                            Label = "ปานกลาง",
                            OrderNo = 3,
                            QuestionId = 8,
                            Score = 2
                        },
                        new
                        {
                            Id = 84,
                            Label = "มาก",
                            OrderNo = 4,
                            QuestionId = 8,
                            Score = 3
                        },
                        new
                        {
                            Id = 91,
                            Label = "ไม่เลย",
                            OrderNo = 1,
                            QuestionId = 9,
                            Score = 0
                        },
                        new
                        {
                            Id = 92,
                            Label = "เล็กน้อย",
                            OrderNo = 2,
                            QuestionId = 9,
                            Score = 1
                        },
                        new
                        {
                            Id = 93,
                            Label = "ปานกลาง",
                            OrderNo = 3,
                            QuestionId = 9,
                            Score = 2
                        },
                        new
                        {
                            Id = 94,
                            Label = "มาก",
                            OrderNo = 4,
                            QuestionId = 9,
                            Score = 3
                        },
                        new
                        {
                            Id = 101,
                            Label = "ไม่เลย",
                            OrderNo = 1,
                            QuestionId = 10,
                            Score = 0
                        },
                        new
                        {
                            Id = 102,
                            Label = "เล็กน้อย",
                            OrderNo = 2,
                            QuestionId = 10,
                            Score = 1
                        },
                        new
                        {
                            Id = 103,
                            Label = "ปานกลาง",
                            OrderNo = 3,
                            QuestionId = 10,
                            Score = 2
                        },
                        new
                        {
                            Id = 104,
                            Label = "มาก",
                            OrderNo = 4,
                            QuestionId = 10,
                            Score = 3
                        },
                        new
                        {
                            Id = 111,
                            Label = "ไม่เลย",
                            OrderNo = 1,
                            QuestionId = 11,
                            Score = 0
                        },
                        new
                        {
                            Id = 112,
                            Label = "เล็กน้อย",
                            OrderNo = 2,
                            QuestionId = 11,
                            Score = 1
                        },
                        new
                        {
                            Id = 113,
                            Label = "ปานกลาง",
                            OrderNo = 3,
                            QuestionId = 11,
                            Score = 2
                        },
                        new
                        {
                            Id = 114,
                            Label = "มาก",
                            OrderNo = 4,
                            QuestionId = 11,
                            Score = 3
                        },
                        new
                        {
                            Id = 121,
                            Label = "ไม่เลย",
                            OrderNo = 1,
                            QuestionId = 12,
                            Score = 0
                        },
                        new
                        {
                            Id = 122,
                            Label = "เล็กน้อย",
                            OrderNo = 2,
                            QuestionId = 12,
                            Score = 1
                        },
                        new
                        {
                            Id = 123,
                            Label = "ปานกลาง",
                            OrderNo = 3,
                            QuestionId = 12,
                            Score = 2
                        },
                        new
                        {
                            Id = 124,
                            Label = "มาก",
                            OrderNo = 4,
                            QuestionId = 12,
                            Score = 3
                        },
                        new
                        {
                            Id = 131,
                            Label = "ไม่เลย",
                            OrderNo = 1,
                            QuestionId = 13,
                            Score = 0
                        },
                        new
                        {
                            Id = 132,
                            Label = "เล็กน้อย",
                            OrderNo = 2,
                            QuestionId = 13,
                            Score = 1
                        },
                        new
                        {
                            Id = 133,
                            Label = "ปานกลาง",
                            OrderNo = 3,
                            QuestionId = 13,
                            Score = 2
                        },
                        new
                        {
                            Id = 134,
                            Label = "มาก",
                            OrderNo = 4,
                            QuestionId = 13,
                            Score = 3
                        },
                        new
                        {
                            Id = 141,
                            Label = "ไม่เลย",
                            OrderNo = 1,
                            QuestionId = 14,
                            Score = 0
                        },
                        new
                        {
                            Id = 142,
                            Label = "เล็กน้อย",
                            OrderNo = 2,
                            QuestionId = 14,
                            Score = 1
                        },
                        new
                        {
                            Id = 143,
                            Label = "ปานกลาง",
                            OrderNo = 3,
                            QuestionId = 14,
                            Score = 2
                        },
                        new
                        {
                            Id = 144,
                            Label = "มาก",
                            OrderNo = 4,
                            QuestionId = 14,
                            Score = 3
                        },
                        new
                        {
                            Id = 151,
                            Label = "ไม่เลย",
                            OrderNo = 1,
                            QuestionId = 15,
                            Score = 0
                        },
                        new
                        {
                            Id = 152,
                            Label = "เล็กน้อย",
                            OrderNo = 2,
                            QuestionId = 15,
                            Score = 1
                        },
                        new
                        {
                            Id = 153,
                            Label = "ปานกลาง",
                            OrderNo = 3,
                            QuestionId = 15,
                            Score = 2
                        },
                        new
                        {
                            Id = 154,
                            Label = "มาก",
                            OrderNo = 4,
                            QuestionId = 15,
                            Score = 3
                        },
                        new
                        {
                            Id = 161,
                            Label = "ไม่เลย",
                            OrderNo = 1,
                            QuestionId = 16,
                            Score = 0
                        },
                        new
                        {
                            Id = 162,
                            Label = "เล็กน้อย",
                            OrderNo = 2,
                            QuestionId = 16,
                            Score = 1
                        },
                        new
                        {
                            Id = 163,
                            Label = "ปานกลาง",
                            OrderNo = 3,
                            QuestionId = 16,
                            Score = 2
                        },
                        new
                        {
                            Id = 164,
                            Label = "มาก",
                            OrderNo = 4,
                            QuestionId = 16,
                            Score = 3
                        },
                        new
                        {
                            Id = 171,
                            Label = "ไม่เลย",
                            OrderNo = 1,
                            QuestionId = 17,
                            Score = 0
                        },
                        new
                        {
                            Id = 172,
                            Label = "เล็กน้อย",
                            OrderNo = 2,
                            QuestionId = 17,
                            Score = 1
                        },
                        new
                        {
                            Id = 173,
                            Label = "ปานกลาง",
                            OrderNo = 3,
                            QuestionId = 17,
                            Score = 2
                        },
                        new
                        {
                            Id = 174,
                            Label = "มาก",
                            OrderNo = 4,
                            QuestionId = 17,
                            Score = 3
                        },
                        new
                        {
                            Id = 181,
                            Label = "ไม่เลย",
                            OrderNo = 1,
                            QuestionId = 18,
                            Score = 0
                        },
                        new
                        {
                            Id = 182,
                            Label = "เล็กน้อย",
                            OrderNo = 2,
                            QuestionId = 18,
                            Score = 1
                        },
                        new
                        {
                            Id = 183,
                            Label = "ปานกลาง",
                            OrderNo = 3,
                            QuestionId = 18,
                            Score = 2
                        },
                        new
                        {
                            Id = 184,
                            Label = "มาก",
                            OrderNo = 4,
                            QuestionId = 18,
                            Score = 3
                        },
                        new
                        {
                            Id = 191,
                            Label = "ไม่เลย",
                            OrderNo = 1,
                            QuestionId = 19,
                            Score = 0
                        },
                        new
                        {
                            Id = 192,
                            Label = "เล็กน้อย",
                            OrderNo = 2,
                            QuestionId = 19,
                            Score = 1
                        },
                        new
                        {
                            Id = 193,
                            Label = "ปานกลาง",
                            OrderNo = 3,
                            QuestionId = 19,
                            Score = 2
                        },
                        new
                        {
                            Id = 194,
                            Label = "มาก",
                            OrderNo = 4,
                            QuestionId = 19,
                            Score = 3
                        },
                        new
                        {
                            Id = 201,
                            Label = "ไม่เลย",
                            OrderNo = 1,
                            QuestionId = 20,
                            Score = 0
                        },
                        new
                        {
                            Id = 202,
                            Label = "เล็กน้อย",
                            OrderNo = 2,
                            QuestionId = 20,
                            Score = 1
                        },
                        new
                        {
                            Id = 203,
                            Label = "ปานกลาง",
                            OrderNo = 3,
                            QuestionId = 20,
                            Score = 2
                        },
                        new
                        {
                            Id = 204,
                            Label = "มาก",
                            OrderNo = 4,
                            QuestionId = 20,
                            Score = 3
                        },
                        new
                        {
                            Id = 211,
                            Label = "ไม่เลย",
                            OrderNo = 1,
                            QuestionId = 21,
                            Score = 0
                        },
                        new
                        {
                            Id = 212,
                            Label = "เล็กน้อย",
                            OrderNo = 2,
                            QuestionId = 21,
                            Score = 1
                        },
                        new
                        {
                            Id = 213,
                            Label = "ปานกลาง",
                            OrderNo = 3,
                            QuestionId = 21,
                            Score = 2
                        },
                        new
                        {
                            Id = 214,
                            Label = "มาก",
                            OrderNo = 4,
                            QuestionId = 21,
                            Score = 3
                        },
                        new
                        {
                            Id = 221,
                            Label = "ไม่เลย",
                            OrderNo = 1,
                            QuestionId = 22,
                            Score = 0
                        },
                        new
                        {
                            Id = 222,
                            Label = "เล็กน้อย",
                            OrderNo = 2,
                            QuestionId = 22,
                            Score = 1
                        },
                        new
                        {
                            Id = 223,
                            Label = "ปานกลาง",
                            OrderNo = 3,
                            QuestionId = 22,
                            Score = 2
                        },
                        new
                        {
                            Id = 224,
                            Label = "มาก",
                            OrderNo = 4,
                            QuestionId = 22,
                            Score = 3
                        },
                        new
                        {
                            Id = 231,
                            Label = "ไม่เลย",
                            OrderNo = 1,
                            QuestionId = 23,
                            Score = 0
                        },
                        new
                        {
                            Id = 232,
                            Label = "เล็กน้อย",
                            OrderNo = 2,
                            QuestionId = 23,
                            Score = 1
                        },
                        new
                        {
                            Id = 233,
                            Label = "ปานกลาง",
                            OrderNo = 3,
                            QuestionId = 23,
                            Score = 2
                        },
                        new
                        {
                            Id = 234,
                            Label = "มาก",
                            OrderNo = 4,
                            QuestionId = 23,
                            Score = 3
                        },
                        new
                        {
                            Id = 241,
                            Label = "ไม่เลย",
                            OrderNo = 1,
                            QuestionId = 24,
                            Score = 0
                        },
                        new
                        {
                            Id = 242,
                            Label = "เล็กน้อย",
                            OrderNo = 2,
                            QuestionId = 24,
                            Score = 1
                        },
                        new
                        {
                            Id = 243,
                            Label = "ปานกลาง",
                            OrderNo = 3,
                            QuestionId = 24,
                            Score = 2
                        },
                        new
                        {
                            Id = 244,
                            Label = "มาก",
                            OrderNo = 4,
                            QuestionId = 24,
                            Score = 3
                        },
                        new
                        {
                            Id = 61,
                            Label = "ไม่มี",
                            OrderNo = 1,
                            QuestionId = 6,
                            Score = 0
                        },
                        new
                        {
                            Id = 62,
                            Label = "มี",
                            OrderNo = 2,
                            QuestionId = 6,
                            Score = 1
                        },
                        new
                        {
                            Id = 71,
                            Label = "ไม่มี",
                            OrderNo = 1,
                            QuestionId = 7,
                            Score = 0
                        },
                        new
                        {
                            Id = 72,
                            Label = "มี",
                            OrderNo = 2,
                            QuestionId = 7,
                            Score = 1
                        });
                });

            modelBuilder.Entity("MindCheck.Domain.Entities.FlowTransition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("condition_type");

                    b.Property<string>("ConditionValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("condition_value");

                    b.Property<int?>("FromInstrumentId")
                        .HasColumnType("integer")
                        .HasColumnName("from_instrument_id");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<int>("ToInstrumentId")
                        .HasColumnType("integer")
                        .HasColumnName("to_instrument_id");

                    b.HasKey("Id")
                        .HasName("pk_flow_transitions");

                    b.ToTable("flow_transitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConditionType = "Always",
                            ToInstrumentId = 1
                        },
                        new
                        {
                            Id = 2,
                            ConditionType = "Always",
                            FromInstrumentId = 1,
                            ToInstrumentId = 2
                        },
                        new
                        {
                            Id = 3,
                            ConditionType = "ScoreLevelEquals",
                            ConditionValue = "Positive",
                            FromInstrumentId = 2,
                            ToInstrumentId = 3
                        },
                        new
                        {
                            Id = 4,
                            ConditionType = "QuestionScoreAtLeast",
                            ConditionValue = "1",
                            FromInstrumentId = 3,
                            QuestionId = 16,
                            ToInstrumentId = 4
                        });
                });

            modelBuilder.Entity("MindCheck.Domain.Entities.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_instruments");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_instruments_code");

                    b.ToTable("instruments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ST5",
                            IsActive = true,
                            Name = "ST-5 (placeholder)",
                            Source = "PLACEHOLDER-DO-NOT-USE-CLINICALLY",
                            Version = "1.0"
                        },
                        new
                        {
                            Id = 2,
                            Code = "2Q",
                            IsActive = true,
                            Name = "2Q (placeholder)",
                            Source = "PLACEHOLDER-DO-NOT-USE-CLINICALLY",
                            Version = "1.0"
                        },
                        new
                        {
                            Id = 3,
                            Code = "9Q",
                            IsActive = true,
                            Name = "9Q (placeholder)",
                            Source = "PLACEHOLDER-DO-NOT-USE-CLINICALLY",
                            Version = "1.0"
                        },
                        new
                        {
                            Id = 4,
                            Code = "8Q",
                            IsActive = true,
                            Name = "8Q (placeholder)",
                            Source = "PLACEHOLDER-DO-NOT-USE-CLINICALLY",
                            Version = "1.0"
                        });
                });

            modelBuilder.Entity("MindCheck.Domain.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer")
                        .HasColumnName("instrument_id");

                    b.Property<int>("OrderNo")
                        .HasColumnType("integer")
                        .HasColumnName("order_no");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("question_type");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_questions_instrument_id");

                    b.ToTable("questions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InstrumentId = 1,
                            OrderNo = 1,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] ST-5 ข้อที่ 1"
                        },
                        new
                        {
                            Id = 2,
                            InstrumentId = 1,
                            OrderNo = 2,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] ST-5 ข้อที่ 2"
                        },
                        new
                        {
                            Id = 3,
                            InstrumentId = 1,
                            OrderNo = 3,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] ST-5 ข้อที่ 3"
                        },
                        new
                        {
                            Id = 4,
                            InstrumentId = 1,
                            OrderNo = 4,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] ST-5 ข้อที่ 4"
                        },
                        new
                        {
                            Id = 5,
                            InstrumentId = 1,
                            OrderNo = 5,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] ST-5 ข้อที่ 5"
                        },
                        new
                        {
                            Id = 6,
                            InstrumentId = 2,
                            OrderNo = 1,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] 2Q ข้อที่ 1"
                        },
                        new
                        {
                            Id = 7,
                            InstrumentId = 2,
                            OrderNo = 2,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] 2Q ข้อที่ 2"
                        },
                        new
                        {
                            Id = 8,
                            InstrumentId = 3,
                            OrderNo = 1,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] 9Q ข้อที่ 1"
                        },
                        new
                        {
                            Id = 9,
                            InstrumentId = 3,
                            OrderNo = 2,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] 9Q ข้อที่ 2"
                        },
                        new
                        {
                            Id = 10,
                            InstrumentId = 3,
                            OrderNo = 3,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] 9Q ข้อที่ 3"
                        },
                        new
                        {
                            Id = 11,
                            InstrumentId = 3,
                            OrderNo = 4,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] 9Q ข้อที่ 4"
                        },
                        new
                        {
                            Id = 12,
                            InstrumentId = 3,
                            OrderNo = 5,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] 9Q ข้อที่ 5"
                        },
                        new
                        {
                            Id = 13,
                            InstrumentId = 3,
                            OrderNo = 6,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] 9Q ข้อที่ 6"
                        },
                        new
                        {
                            Id = 14,
                            InstrumentId = 3,
                            OrderNo = 7,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] 9Q ข้อที่ 7"
                        },
                        new
                        {
                            Id = 15,
                            InstrumentId = 3,
                            OrderNo = 8,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] 9Q ข้อที่ 8"
                        },
                        new
                        {
                            Id = 16,
                            InstrumentId = 3,
                            OrderNo = 9,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] 9Q ข้อที่ 9"
                        },
                        new
                        {
                            Id = 17,
                            InstrumentId = 4,
                            OrderNo = 1,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] 8Q ข้อที่ 1"
                        },
                        new
                        {
                            Id = 18,
                            InstrumentId = 4,
                            OrderNo = 2,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] 8Q ข้อที่ 2"
                        },
                        new
                        {
                            Id = 19,
                            InstrumentId = 4,
                            OrderNo = 3,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] 8Q ข้อที่ 3"
                        },
                        new
                        {
                            Id = 20,
                            InstrumentId = 4,
                            OrderNo = 4,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] 8Q ข้อที่ 4"
                        },
                        new
                        {
                            Id = 21,
                            InstrumentId = 4,
                            OrderNo = 5,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] 8Q ข้อที่ 5"
                        },
                        new
                        {
                            Id = 22,
                            InstrumentId = 4,
                            OrderNo = 6,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] 8Q ข้อที่ 6"
                        },
                        new
                        {
                            Id = 23,
                            InstrumentId = 4,
                            OrderNo = 7,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] 8Q ข้อที่ 7"
                        },
                        new
                        {
                            Id = 24,
                            InstrumentId = 4,
                            OrderNo = 8,
                            QuestionType = "SingleChoice",
                            Text = "[PLACEHOLDER] 8Q ข้อที่ 8"
                        });
                });

            modelBuilder.Entity("MindCheck.Domain.Entities.Response", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<int>("ChoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("choice_id");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_responses");

                    b.HasIndex("SessionId", "QuestionId")
                        .HasDatabaseName("ix_responses_session_id_question_id");

                    b.ToTable("responses", (string)null);
                });

            modelBuilder.Entity("MindCheck.Domain.Entities.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer")
                        .HasColumnName("instrument_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("level");

                    b.Property<string>("NextAction")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("next_action");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_score");

                    b.HasKey("Id")
                        .HasName("pk_results");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_results_session_id");

                    b.ToTable("results", (string)null);
                });

            modelBuilder.Entity("MindCheck.Domain.Entities.RiskRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer")
                        .HasColumnName("instrument_id");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("pk_risk_rules");

                    b.ToTable("risk_rules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "emergency",
                            InstrumentId = 4,
                            QuestionId = 24
                        });
                });

            modelBuilder.Entity("MindCheck.Domain.Entities.ScoringRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Advice")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("advice");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer")
                        .HasColumnName("instrument_id");

                    b.Property<string>("Interpretation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("interpretation");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("level");

                    b.HasKey("Id")
                        .HasName("pk_scoring_rules");

                    b.ToTable("scoring_rules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Advice = "[PLACEHOLDER] คำแนะนำระดับต่ำ",
                            InstrumentId = 1,
                            Interpretation = "[PLACEHOLDER] ระดับความเครียดต่ำ",
                            Level = "Low"
                        },
                        new
                        {
                            Id = 2,
                            Advice = "[PLACEHOLDER] คำแนะนำระดับปานกลาง",
                            InstrumentId = 1,
                            Interpretation = "[PLACEHOLDER] ระดับความเครียดปานกลาง",
                            Level = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            Advice = "[PLACEHOLDER] คำแนะนำระดับสูง",
                            InstrumentId = 1,
                            Interpretation = "[PLACEHOLDER] ระดับความเครียดสูง",
                            Level = "High"
                        },
                        new
                        {
                            Id = 4,
                            Advice = "[PLACEHOLDER] คำแนะนำ",
                            InstrumentId = 2,
                            Interpretation = "[PLACEHOLDER] ไม่พบสัญญาณ",
                            Level = "Negative"
                        },
                        new
                        {
                            Id = 5,
                            Advice = "[PLACEHOLDER] คำแนะนำ",
                            InstrumentId = 2,
                            Interpretation = "[PLACEHOLDER] พบสัญญาณ ควรประเมินต่อ",
                            Level = "Positive"
                        },
                        new
                        {
                            Id = 6,
                            Advice = "[PLACEHOLDER] คำแนะนำ",
                            InstrumentId = 3,
                            Interpretation = "[PLACEHOLDER] ระดับต่ำ",
                            Level = "Low"
                        },
                        new
                        {
                            Id = 7,
                            Advice = "[PLACEHOLDER] คำแนะนำ",
                            InstrumentId = 3,
                            Interpretation = "[PLACEHOLDER] ระดับปานกลาง",
                            Level = "Medium"
                        },
                        new
                        {
                            Id = 8,
                            Advice = "[PLACEHOLDER] คำแนะนำ",
                            InstrumentId = 3,
                            Interpretation = "[PLACEHOLDER] ระดับสูง",
                            Level = "High"
                        },
                        new
                        {
                            Id = 9,
                            Advice = "[PLACEHOLDER] คำแนะนำ",
                            InstrumentId = 4,
                            Interpretation = "[PLACEHOLDER] ระดับต่ำ",
                            Level = "Low"
                        },
                        new
                        {
                            Id = 10,
                            Advice = "[PLACEHOLDER] คำแนะนำ",
                            InstrumentId = 4,
                            Interpretation = "[PLACEHOLDER] ระดับปานกลาง",
                            Level = "Medium"
                        },
                        new
                        {
                            Id = 11,
                            Advice = "[PLACEHOLDER] คำแนะนำ",
                            InstrumentId = 4,
                            Interpretation = "[PLACEHOLDER] ระดับสูง",
                            Level = "High"
                        });
                });

            modelBuilder.Entity("MindCheck.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnonToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("anon_token");

                    b.Property<DateTimeOffset?>("ConsentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consent_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("current_state");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("AnonToken")
                        .IsUnique()
                        .HasDatabaseName("ix_sessions_anon_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sessions_user_id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("MindCheck.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("password_reset_token");

                    b.Property<DateTimeOffset?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_token_expires_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("PasswordResetToken")
                        .HasDatabaseName("ix_users_password_reset_token");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MindCheck.Domain.Entities.Choice", b =>
                {
                    b.HasOne("MindCheck.Domain.Entities.Question", null)
                        .WithMany("Choices")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_choices_questions_question_id");
                });

            modelBuilder.Entity("MindCheck.Domain.Entities.Question", b =>
                {
                    b.HasOne("MindCheck.Domain.Entities.Instrument", null)
                        .WithMany("Questions")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_instruments_instrument_id");
                });

            modelBuilder.Entity("MindCheck.Domain.Entities.RiskRule", b =>
                {
                    b.OwnsOne("MindCheck.Domain.ValueObjects.RiskCondition", "Condition", b1 =>
                        {
                            b1.Property<int>("RiskRuleId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Operator")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("operator");

                            b1.Property<int>("Threshold")
                                .HasColumnType("integer")
                                .HasColumnName("threshold");

                            b1.HasKey("RiskRuleId");

                            b1.ToTable("risk_rules");

                            b1.WithOwner()
                                .HasForeignKey("RiskRuleId")
                                .HasConstraintName("fk_risk_rules_risk_rules_id");

                            b1.HasData(
                                new
                                {
                                    RiskRuleId = 1,
                                    Operator = "GreaterThanOrEqual",
                                    Threshold = 1
                                });
                        });

                    b.Navigation("Condition")
                        .IsRequired();
                });

            modelBuilder.Entity("MindCheck.Domain.Entities.ScoringRule", b =>
                {
                    b.OwnsOne("MindCheck.Domain.ValueObjects.ScoreRange", "Range", b1 =>
                        {
                            b1.Property<int>("ScoringRuleId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<int>("Max")
                                .HasColumnType("integer")
                                .HasColumnName("max_score");

                            b1.Property<int>("Min")
                                .HasColumnType("integer")
                                .HasColumnName("min_score");

                            b1.HasKey("ScoringRuleId");

                            b1.ToTable("scoring_rules");

                            b1.WithOwner()
                                .HasForeignKey("ScoringRuleId")
                                .HasConstraintName("fk_scoring_rules_scoring_rules_id");

                            b1.HasData(
                                new
                                {
                                    ScoringRuleId = 1,
                                    Max = 4,
                                    Min = 0
                                },
                                new
                                {
                                    ScoringRuleId = 2,
                                    Max = 9,
                                    Min = 5
                                },
                                new
                                {
                                    ScoringRuleId = 3,
                                    Max = 15,
                                    Min = 10
                                },
                                new
                                {
                                    ScoringRuleId = 4,
                                    Max = 0,
                                    Min = 0
                                },
                                new
                                {
                                    ScoringRuleId = 5,
                                    Max = 2,
                                    Min = 1
                                },
                                new
                                {
                                    ScoringRuleId = 6,
                                    Max = 9,
                                    Min = 0
                                },
                                new
                                {
                                    ScoringRuleId = 7,
                                    Max = 19,
                                    Min = 10
                                },
                                new
                                {
                                    ScoringRuleId = 8,
                                    Max = 27,
                                    Min = 20
                                },
                                new
                                {
                                    ScoringRuleId = 9,
                                    Max = 7,
                                    Min = 0
                                },
                                new
                                {
                                    ScoringRuleId = 10,
                                    Max = 15,
                                    Min = 8
                                },
                                new
                                {
                                    ScoringRuleId = 11,
                                    Max = 24,
                                    Min = 16
                                });
                        });

                    b.Navigation("Range")
                        .IsRequired();
                });

            modelBuilder.Entity("MindCheck.Domain.Entities.Instrument", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("MindCheck.Domain.Entities.Question", b =>
                {
                    b.Navigation("Choices");
                });
#pragma warning restore 612, 618
        }
    }
}
